Fix build: test/ missing CommandControl.cpp
happens in my clang build after 0ac620bc50bfce11cb25a598eb829905ff966a03

online/test/../wsd/HostUtil.cpp:147:(.text+0x1929): undefined reference to `CommandControl::LockManager::unlockLinkMap[abi:cxx11]'

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: I7759fbf6a7ac2da36aa76c6e6f3e55962b324f90