Revive COWASM: Fix missing linker symbols
The online_SOURCES in wasm/Makefile.am had presumably gone stale for various
reasons, so just add more source files to it until there are no further missing
symbol linker errors.  But then the existing implementation of
platformDependentCheckDiskSpace in common/FileUtil-unix.cpp would cause

> wasm/../common/FileUtil-unix.cpp:76:23: error: variable has incomplete type 'struct statfs'
>    76 |         struct statfs sfs;
>       |                       ^

so for now just add an empty implementation of that function with a TODO marker
for the __EMSCRIPTEN__ case.

Signed-off-by: Stephan Bergmann <stephan.bergmann@allotropia.de>
Change-Id: Ia5498e87701686eefa9b1eb59ae7a9f9f41cf523