zoom: add required method to base view
We got error when changing page size in mutli-page view:
global.js:598 Exception TypeError: app.activeDocument.activeLayout.getDocumentScrollOffset is not a function

Missing method comes from:
commit db0011166aa49caa1196e0087a68e94f5f635dba
enhancement: make document movements smooth when making space for comments

This mistake is caused by the class hierarchy:
We have ViewLayoutWriter which inherits from a base class,
but ViewLayoutMultiPage or Compare are also for Writer...

For now let's use the new comment-positioning code only in the
layout which was adjusted for them in mentioned commit.

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: Ifb3157d6acab2446f7b7f9be76322a69b2dde7db