fix Exception TypeError due to NaN
Exception TypeError: Failed to execute 'fromMatrix' on 'DOMMatrix': The is2D member is set to true but the input matrix is a 3d matrix. emitting event slideshowfollow dispatcheffect
TypeError: The is2D member is set to true but the input matrix is a 3d matrix.
    at AnimatedElement.saveState (AnimatedElement.ts:934:24)
    at AnimationBaseNode.saveStateOfAnimatedElement (AnimationBaseNode.ts:179:29)
    at AnimationBaseNode.activate_st (AnimationBaseNode.ts:120:9)
    at BaseNode.activate (BaseNode.ts:487:9)
    at DelayEvent.fire (Event.ts:53:8)
    at TimerEventQueue.process_ (TimerEventQueue.ts:57:35)
    at TimerEventQueue.process (TimerEventQueue.ts:43:8)
    at SlideShowHandler.update (SlideShowHandler.ts:973:25)
    at SlideShowHandler.nextEffect (SlideShowHandler.ts:549:8)
    at SlideShowNavigator.dispatchEffect (SlideShowNavigator.ts:123:38)

Signed-off-by: Mohit Marathe <mohit.marathe@collabora.com>
Change-Id: Ieeb5432640752364b5c9531632bafade2e5df910