CODA-Q flatpak: --enable-symbols for libreoffice module
...so that its debug information will end up in the org.collabora.CODA.Debug
extension (which is the only artifact that will increase in size; the main
org.collabora.CODA app will remain at its previous size).

For whatever reason, --enable-symbols would cause the build to fail with

> stripping /home/sberg/coda-q-flatpak/.flatpak-builder/rofiles/rofiles-PMEbRO/files/collaboraoffice/program/libnspr4.so to /home/sberg/coda-q-flatpak/.flatpak-builder/rofiles/rofiles-PMEbRO/files/lib/debug/collaboraoffice/program/libnspr4.so.debug
> eu-strip: while opening '/home/sberg/coda-q-flatpak/.flatpak-builder/rofiles/rofiles-PMEbRO/files/collaboraoffice/program/libnspr4.so': Permission denied
> Error: module libreoffice: Child process exited with code 1

but adding --without-system-nss in bb6337d9b49c3be52d69cc762a40e7f8ccbe8364
"CODA-Q: flatpak: combination of original flatpak config and CPLinux-LOKit
config for core" was arguably misguided, anyway, so drop that again to fix the
--enable-symbols build.

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I554107fed1a2b4a26f2e42c29eab211a60b4a073