fix configure check 'If we need to link with -lpcre'
The test program did not compile because of
error: unused parameter 'argc' [-Werror=unused-parameter]
As result, we always linked with -lpcre.

Change-Id: I7557025cc56fb72fc2a9f8de6142de93cfed2335
Reviewed-on: https://gerrit.libreoffice.org/81766
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Andras Timar <andras.timar@collabora.com>