Fix clang warning about unused functions
wsd/ClientRequestDispatcher.cpp:1106:1: error: unused function 'toStringShort' [-Werror,-Wunused-function]
STATE_ENUM(CheckStatus,
^
./common/StateEnum.hpp:63:31: note: expanded from macro 'STATE_ENUM'
    static inline std::string toStringShort(NAME e)                                                \
                              ^
wsd/ClientRequestDispatcher.cpp:1106:1: error: unused function 'toString' [-Werror,-Wunused-function]
./common/StateEnum.hpp:76:31: note: expanded from macro 'STATE_ENUM'
    static inline std::string toString(NAME e)                                                     \
                              ^
wsd/ClientRequestDispatcher.cpp:1106:1: error: unused variable 'CheckStatusMax' [-Werror,-Wunused-const-variable]
./common/StateEnum.hpp:80:25: note: expanded from macro 'STATE_ENUM'
    static const size_t NAME##Max = COUNT_ARGS(__VA_ARGS__);                                       \
                        ^
<scratch space>:107:1: note: expanded from here
CheckStatusMax
^
3 errors generated.

introduced by commit e116ee8f0a4e16ad5b74918a9c1bce57d18a3377
Add an endpoint to check connectivity to WOPI server

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: I9bfc67dee4c68563c8c750172ee7caef36fedfa1