cypress: try to handle support file better during parallel run.
When we run cypress tests in parallel (e.g. make check -j4), the
tests randomly fail with an uncaught error. The issue might be
because the same support file is shared between the different threads,
and they might access it at the same time. We try to create different
instances of the support file via preprocessing. Let's see whether it
makes the issue go away.

Issue's error message was:
"An uncaught error was detected outside of a test:
SyntaxError: The following error originated from your test code, not from Cypress.
Unexpected end of input"

Signed-off-by: Tamás Zolnai <tamas.zolnai@collabora.com>
Change-Id: I7b256cd686fb2b0e79ab602e95d197388a5aadca
(cherry picked from commit a13b1a93bca1a6fe4ef0efc11156974ebb66a29f)