annotations: check instance before use
- error catched by cypress:
      cy:command ✘  uncaught exception	TypeError: Cannot read properties of undefined (reading 'sectionProperties')
      cy:command ✔  error:	Cannot read properties of undefined (reading 'sectionProperties')
                    TypeError: Cannot read properties of undefined (reading 'sectionProperties')
                        at CommentSection.scrollCommentIntoView (http://localhost:9900/browser/df022548db/src/canvas/sections/CommentListSection.js:831:30)

- we need to make that file not ignored for strict checking

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: Id52da6cda4fcda3d686f3799a08f641e5312cd8e