Check LayerRenderer is disposed before drawBitmap
When user stopped presentation early, online still tries to draw slides
because of delayed "slidelayer" messages from core. That is the cause of
following error

TypeError: Cannot read properties of null (reading 'useProgram')

So we shold check if the user exited from presentation before drawing slides.

Signed-off-by: Gülşah Köse <gulsah.kose@collabora.com>
Change-Id: If3b3cb340cfc15632de16d0fed1c730ab4d9d763