typescript: fix errors on accessing unknown property
src/canvas/CanvasSectionContainer.ts:1540:74 - error TS2339: Property 'length' does not exist on type 'never'.

1540   if (typeof section.anchor[index] === 'string' || section.anchor[index].length === 1) {
                                                                              ~~~~~~

src/canvas/CanvasSectionContainer.ts:1552:30 - error TS2339: Property 'length' does not exist on type 'never'.

1552    if (section.anchor[index].length % 2 === 0) { // eslint-disable-line no-lonely-if
                                  ~~~~~~

src/canvas/CanvasSectionContainer.ts:1557:47 - error TS2339: Property 'length' does not exist on type 'never'.

1557     var count: number = section.anchor[index].length;
                                                   ~~~~~~

Found 3 errors in the same file, starting at: src/canvas/CanvasSectionContainer.ts:1540

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: Ifa48ea0df5a915c13c9e242122f0acfa202715e2