git-commit: Skip code formatting check when no Makefile is found
...because e.g. we are committing from a source tree that is not used for
building (because e.g. the build is done out-of-tree), which previously would
have failed with an unhelpful

> ===============================================
>   ERROR: Code formatting check failed
> ===============================================
> Your code is not properly formatted.
> Please run 'gmake prettier-write' before committing.
> ===============================================

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I7275467ffddb4a9efaeb0e4415bdded876a7d274