canvas: remove not exising function call
when closing the COOL I saw unhandled exception:
TypeError: this.stopUpdates is not a function

that function doesn't exist in the current code base

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: Ib38d01fe44a766eec57239e48e9833bfd232bec2