Avoid error on close
browser/a510bb2f78/src/layer/tile/CanvasTileLayer.js:3360 Uncaught TypeError: this._painter.dispose is not a function
    at NewClass.onRemove (/browser/a510bb2f78/src/layer/tile/CanvasTileLayer.js:3360:23)

dispose doesn't exist

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: I80cde8b5ef2205dad39bdc69f30940bec2e601d4