Separate cat'ed *.js files with newlines
...as --enable-debug causes node_modules/typescript/bin/tsc to be called with
`--sourceMap true`, which causes it to append

> //# sourceMappingURL=[...].js.map

lines without a final newline to the end of the generated *.js files, which
caused an --enable-debug --enable-bundle build to generate a broken
browser/release/bundle.js

[...]
> }());
> app.events.on('updatepermission', GraphicSelection.onUpdatePermission.bind(GraphicSelection));
> app.definitions.graphicSelection = GraphicSelection;
> //# sourceMappingURL=GraphicSelectionMiddleware.js.map/*
>  * Copyright the Collabora Online contributors.
>  *
>  * SPDX-License-Identifier: MPL-2.0
[...]

causing

> Uglify cool js files...
> Parse error at /home/sberg/cool/online/browser/release/bundle.js:51490,1
>  * Copyright the Collabora Online contributors.
>  ^
> ERROR: Unexpected token: operator «*»

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: Idb117b020596ef77cf46b5cde933531cb85b424a