cypress: ignore pixel difference in scroll position
- often fails on:
  AssertionError: Timed out retrying after 10000ms: expected 251 to be within 250..250

- which is not a visible difference

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: I280b224ca1215116a63c2cd9caec363161a2d691