Fix --enable-gtkapp build
...after 2d83187c764ad69457bdb47efd6050b96af82da9 "add Util::trimMalloc" caused
it to fail with

> gtk/../common/Util.cpp:804:65: error: ‘RTLD_NEXT’ was not declared in this scope
>   804 |             auto symbol = reinterpret_cast<void(*)(void)>(dlsym(RTLD_NEXT, "MallocExtension_ReleaseFreeMemory"));
>       |                                                                 ^~~~~~~~~
> gtk/../common/Util.cpp:804:59: error: ‘dlsym’ was not declared in this scope
>   804 |             auto symbol = reinterpret_cast<void(*)(void)>(dlsym(RTLD_NEXT, "MallocExtension_ReleaseFreeMemory"));
>       |                                                           ^~~~~

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I5604d38d2a99be5e040326c2cf671f4077731d8c