Check if selection exists before use #15515
Fixes #15515

Steps to reproduce:
- Open Calc
- Switch to View-Only mode (top right corner)
- triple click any cell with text (select text inside cell)

Result: error

Exception TypeError: Cannot read properties of undefined (reading 'left') emitting event jsdialog: { "jsontype": "formulabar", "action": "action", "id": 0, "data": { "control_id": "sc_input_window", "separator": ".", "selection": "0;2;0;0", "text": "gg", "action_type": "setText"}}
TypeError: Cannot read properties of undefined (reading 'left')
    at _setSelection (Widget.FormulabarEdit.js:341:70)
    at container.setText (Widget.FormulabarEdit.js:417:3)
    at FormulaBar.onJSAction (Control.FormulaBarJSDialog.js:341:21)

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: Iab3fb30dc177d9ce98e87fd80fa2fd94838e49c2