Catch errors on RTL sheet load
When loading some RTL sheets sometimes I got errors on
load which caused lack of some UI elements.

global.js:566 Exception TypeError: Cannot read properties of undefined (reading 'getSplitPos') emitting event commandvalues: { "commandName": ".uno:CellCursor", "commandValues": "7680, 9728, 1279, 255, 6, 38"}
TypeError: Cannot read properties of undefined (reading 'getSplitPos')
    at NewClass._calculateScrollForNewCellCursor (http://localhost:9980/browser/2e02d4f82b/src/layer/tile/CalcTileLayer.js:940:47)
    at NewClass._onUpdateCellCursor (http://localhost:9980/browser/2e02d4f82b/src/layer/tile/CanvasTileLayer.js:2916:35)

VM904 global.js:566 Exception TypeError: Cannot set properties of null (setting 'anchor') emitting event status: {"mode": 0,"readonly": false,"lastrow": 138,"viewid": 4,"height": 35310,"lastcolumn": 41,"width": 53611,"parts": [{ "visible": 0, "rtllayout": 0, "protected": 0, "selected": 0, "name": "Tabelle1", "hash": 93830215353248, "lastcolumn": 38, "lastrow": 382}, { "visible": 1, "rtllayout": 0, "protected": 0, "selected": 0, "name": "Sheet2", "hash": 93830217837952, "lastcolumn": 0, "lastrow": 0}, { "visible": 1, "rtllayout": 0, "protected": 0, "selected": 0, "name": "Sheet3", "hash": 93830217863568, "lastcolumn": 0, "lastrow": 0}, { "visible": 1, "rtllayout": 0, "protected": 0, "selected": 0, "name": "Sheet4", "hash": 93830217881088, "lastcolumn": 0, "lastrow": 0}, { "visible": 1, "rtllayout": 1, "protected": 0, "selected": 0, "name": "Sheet5", "hash": 93830217897104, "lastcolumn": 41, "lastrow": 138}],"selectedpart": 4,"partscount": 5,"type": "spreadsheet"}
TypeError: Cannot set properties of null (setting 'anchor')
    at NewClass._adjustCanvasSectionsForLayoutChange (http://localhost:9980/browser/2e02d4f82b/src/layer/tile/CalcTileLayer.js:564:40)
    at NewClass._onStatusMsg (http://localhost:9980/browser/2e02d4f82b/src/layer/tile/CalcTileLayer.js:376:18)

Signed-off-by: Szymon Kłos <szymon.klos@collabora.com>
Change-Id: I449c3ed77a3c2322cde65cad8737e93785dfbabd