loolwsd: release lokit after destroy it
In order to avoid:

Error: "double free or corruption (fasttop)"

lokit cannot be deleted, instead it is used loKit->pClass->destroy