CODA-Q: Add missing object file
...to avoid

> make[3]: Entering directory '/home/sberg/coda-q/online/qt'
> /bin/sh ../libtool  --tag=CXX   --mode=link g++  -fdiagnostics-color=always -g  -grecord-gcc-switches -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -fstack-clash-protection -fcf-protection -std=c++20 -Werror -pthread -lQt6WebEngineWidgets -lQt6WebEngineCore -lQt6Quick -lQt6QmlMeta -lQt6QmlWorkerScript -lQt6QmlModels -lQt6OpenGL -lQt6WebChannel -lQt6Qml -lQt6Network -lQt6Positioning -lQt6PrintSupport -lQt6Widgets -lQt6Gui -lQt6DBus -lQt6Core -ldl -lzstd -lpng16 -lPocoZip  -o coda-qt coda-qt.o WebView.o DBusService.o bridge.moc.o DBusService.moc.o ../common/Authorization.o ../common/ConfigUtil.o ../common/CommandControl.o ../common/Crypto-stub.o ../common/FileUtil.o ../common/FileUtil-unix.o ../common/Log-common.o ../common/Log-poco.o ../common/MobileApp.o ../common/TraceEvent.o ../common/Protocol.o ../common/RegexUtil.o ../common/Simd.o ../common/StringVector.o ../common/Session.o ../common/SigUtil-mobile.o ../common/SpookyV2.o ../common/Unit.o ../common/Unit-mobile.o ../common/Util.o ../common/Util-mobile.o ../common/Util-unix.o ../common/Uri.o ../kit/ChildSession.o ../kit/DeltaSimd.o ../kit/Kit.o ../kit/KitQueue.o ../kit/LogUI.o ../kit/KitWebSocket.o ../net/FakeSocket.o ../net/Socket.o ../wsd/ClientSession.o ../wsd/DocumentBroker.o ../wsd/COOLWSD.o ../wsd/ClientRequestDispatcher.o ../wsd/RequestDetails.o ../wsd/RequestVettingStation.o ../wsd/Storage.o ../wsd/TileCache.o ../wsd/coolwsd-fork.o ../wsd/dumpWsdState.o  -lcap  -lPocoNetSSL -lPocoNet -lPocoUtil -lPocoJSON -lPocoXML -lPocoFoundation -lPocoCrypto
> libtool: link: g++ -fdiagnostics-color=always -g -grecord-gcc-switches -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -fstack-clash-protection -fcf-protection -std=c++20 -Werror -o coda-qt coda-qt.o WebView.o DBusService.o bridge.moc.o DBusService.moc.o ../common/Authorization.o ../common/ConfigUtil.o ../common/CommandControl.o ../common/Crypto-stub.o ../common/FileUtil.o ../common/FileUtil-unix.o ../common/Log-common.o ../common/Log-poco.o ../common/MobileApp.o ../common/TraceEvent.o ../common/Protocol.o ../common/RegexUtil.o ../common/Simd.o ../common/StringVector.o ../common/Session.o ../common/SigUtil-mobile.o ../common/SpookyV2.o ../common/Unit.o ../common/Unit-mobile.o ../common/Util.o ../common/Util-mobile.o ../common/Util-unix.o ../common/Uri.o ../kit/ChildSession.o ../kit/DeltaSimd.o ../kit/Kit.o ../kit/KitQueue.o ../kit/LogUI.o ../kit/KitWebSocket.o ../net/FakeSocket.o ../net/Socket.o ../wsd/ClientSession.o ../wsd/DocumentBroker.o ../wsd/COOLWSD.o ../wsd/ClientRequestDispatcher.o ../wsd/RequestDetails.o ../wsd/RequestVettingStation.o ../wsd/Storage.o ../wsd/TileCache.o ../wsd/coolwsd-fork.o ../wsd/dumpWsdState.o  -lQt6WebEngineWidgets -lQt6WebEngineCore -lQt6Quick -lQt6QmlMeta -lQt6QmlWorkerScript -lQt6QmlModels -lQt6OpenGL -lQt6WebChannel -lQt6Qml -lQt6Network -lQt6Positioning -lQt6PrintSupport -lQt6Widgets -lQt6Gui -lQt6DBus -lQt6Core -ldl -lzstd -lpng16 -lPocoZip -lcap -lPocoNetSSL -lPocoNet -lPocoUtil -lPocoJSON -lPocoXML -lPocoFoundation -lPocoCrypto -pthread
> /usr/bin/ld: ../wsd/ClientSession.o: in function `DocumentBroker::invalidateSlideLayerCache()':
> /home/sberg/coda-q/online/qt/../wsd/DocumentBroker.hpp:436:(.text._ZN14DocumentBroker25invalidateSlideLayerCacheEv[_ZN14DocumentBroker25invalidateSlideLayerCacheEv]+0x1e): undefined reference to `SlideLayerCacheMap::erase_all()'
> /usr/bin/ld: ../wsd/DocumentBroker.o: in function `DocumentBroker::handleGetSlideRequest(StringVector const&, std::shared_ptr<ClientSession>)':
> /home/sberg/coda-q/online/qt/../wsd/DocumentBroker.cpp:4672:(.text+0x2ac90): undefined reference to `SlideLayerCacheMap::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> /usr/bin/ld: /home/sberg/coda-q/online/qt/../wsd/DocumentBroker.cpp:4672:(.text+0x2acac): undefined reference to `SlideLayerCacheMap::end[abi:cxx11]()'
> /usr/bin/ld: ../wsd/DocumentBroker.o: in function `DocumentBroker::handleSlideLayerResponse(std::shared_ptr<Message> const&)':
> /home/sberg/coda-q/online/qt/../wsd/DocumentBroker.cpp:4698:(.text+0x2b3fc): undefined reference to `SlideLayerCacheMap::insert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<Message>)'
> collect2: error: ld returned 1 exit status
> make[3]: *** [Makefile:814: coda-qt] Error 1
> make[3]: Leaving directory '/home/sberg/coda-q/online/qt'

which started to hit now

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I46dc3d51b8de8cd8eb964e7b01f721a7b696d362